# Site settings
title: Praqma
email: info@praqma.net
logo: /images/logo.png
description: The Continuous Delivery Company
slogan: — In Praqma we strive to change the world…
url: http://praqma.com

# Build settings
markdown: kramdown

sass:
  #sass_dir: bower_components/bootstrap-sass/assets/stylesheets

permalink: /:categories/:title/

collections:
  training:
    output: true
    permalink: /training/:path/

defaults:
  -
    scope:
      path: "" # any file
    values:
      layout: page
  -
    scope:
      type: posts
    values:
      categories: blog
      layout: post
  -
    scope:
      path: pages/tags
    values:
      categories: [tag-page, blog] #it goes into body classes and impacts on styles
      #categories: tag-page
      permalink: /blog/:basename/
      layout: tag-page
  #-
    #scope:
      ##path: pages/training
      #path: ""
      #type: training
    #values:
      #layout: page
      #already a default for all
