# Site settings
title: Praqma
email: info@praqma.net
logo: /images/logo.png
description: The Continuous Delivery Company
slogan: — In Praqma we strive to change the world…
url: http://praqma.com

# Build settings
markdown: kramdown

sass:
  #sass_dir: bower_components/bootstrap-sass/assets/stylesheets

defaults:
  -
    scope:
      path: "" # any file
    values:
      layout: page
